powershell -command %OMS_HOME%\purgeLogs.ps1 -name "pmc"
powershell -command %OMS_HOME%\purgeLogs.ps1 -name "pmcError" -error "Y"
powershell -command %OMS_HOME%\purgeLogs.ps1 -name "simError" -error "Y"
powershell -command %OMS_HOME%\purgeLogs.ps1 -name "simulate"
powershell -command %OMS_HOME%\purgeLogs.ps1 -name "transfer"
powershell -command %OMS_HOME%\purgeLogs.ps1 -name "transferError" -error "Y"
powershell -command %OMS_HOME%\purgeLogs.ps1 -name "watchdog"
powershell -command %OMS_HOME%\purgeLogs.ps1 -name "wdError" -error "Y"
